/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecsIndexRouteImport } from './routes/specs.index'
import { Route as SpecsNewRouteImport } from './routes/specs.new'
import { Route as SpecsIdRouteImport } from './routes/specs.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsIndexRoute = SpecsIndexRouteImport.update({
  id: '/specs/',
  path: '/specs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsNewRoute = SpecsNewRouteImport.update({
  id: '/specs/new',
  path: '/specs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsIdRoute = SpecsIdRouteImport.update({
  id: '/specs/$id',
  path: '/specs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/specs/$id': typeof SpecsIdRoute
  '/specs/new': typeof SpecsNewRoute
  '/specs/': typeof SpecsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/specs/$id': typeof SpecsIdRoute
  '/specs/new': typeof SpecsNewRoute
  '/specs': typeof SpecsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/specs/$id': typeof SpecsIdRoute
  '/specs/new': typeof SpecsNewRoute
  '/specs/': typeof SpecsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/specs/$id' | '/specs/new' | '/specs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/specs/$id' | '/specs/new' | '/specs'
  id: '__root__' | '/' | '/login' | '/specs/$id' | '/specs/new' | '/specs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SpecsIdRoute: typeof SpecsIdRoute
  SpecsNewRoute: typeof SpecsNewRoute
  SpecsIndexRoute: typeof SpecsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs/': {
      id: '/specs/'
      path: '/specs'
      fullPath: '/specs/'
      preLoaderRoute: typeof SpecsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs/new': {
      id: '/specs/new'
      path: '/specs/new'
      fullPath: '/specs/new'
      preLoaderRoute: typeof SpecsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs/$id': {
      id: '/specs/$id'
      path: '/specs/$id'
      fullPath: '/specs/$id'
      preLoaderRoute: typeof SpecsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SpecsIdRoute: SpecsIdRoute,
  SpecsNewRoute: SpecsNewRoute,
  SpecsIndexRoute: SpecsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
